/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form_racun;

import controller.ClientController;
import domain.Klijent;
import domain.Krojacica;
import domain.Racun;
import domain.StavkaRacuna;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import models.TableModelStavkeRacuna;

/**
 *
 * @author Andjela
 */
public class FormDetaljiRacuna extends javax.swing.JDialog {

    private Racun r;
    private FormPretragaRacuna fpr;

    /**
     * Creates new form FormDetaljiRacuna
     */
    public FormDetaljiRacuna(JDialog parent, boolean modal, Racun r) {
        super(parent, modal);
        initComponents();
        this.fpr = (FormPretragaRacuna) parent;
        popuniKlijente();
        popuniKrojacice();
        setLocationRelativeTo(null);
        setTitle("Detalji racuna");

        try {
            this.r = ClientController.getInstance().pretraziRacun(r);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje racun.");
            this.dispose();
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
        jTextFieldDatum.setText(sdf.format(this.r.getDatumIzdavanja()));
        jTextFieldMesto.setText(this.r.getMestoIzdavanja());
        jTextFieldUkupanIznos.setText(String.valueOf(this.r.getUkupanIznos()));
        jComboBoxKlijent.setSelectedItem(this.r.getKlijent());
        jComboBoxKrojacica.setSelectedItem(this.r.getKrojacica());

        jTableStavke.setModel(new TableModelStavkeRacuna(this.r.getStavkeRacuna()));

        jTextFieldDatum.setEnabled(false);
        jTextFieldMesto.setEnabled(false);
        jTextFieldUkupanIznos.setEnabled(false);
        jComboBoxKlijent.setEnabled(false);
        jComboBoxKrojacica.setEnabled(false);
        jButtonSacuvaj.setEnabled(false);
        jButtonObrisiStavku.setEnabled(false);
        jButtonIzmeniStavku.setEnabled(false);
        jButtonDodajStavku.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldDatum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMesto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUkupanIznos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStavke = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButtonZatvori = new javax.swing.JButton();
        jButtonIzmeni = new javax.swing.JButton();
        jButtonSacuvaj = new javax.swing.JButton();
        jComboBoxKlijent = new javax.swing.JComboBox<>();
        jComboBoxKrojacica = new javax.swing.JComboBox<>();
        jButtonObrisiStavku = new javax.swing.JButton();
        jButtonIzmeniStavku = new javax.swing.JButton();
        jButtonDodajStavku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Datum:");

        jLabel2.setText("Mesto:");

        jLabel3.setText("Ukupan iznos:");

        jLabel4.setText("Klijent:");

        jLabel5.setText("Krojacica:");

        jLabel6.setText("din.");

        jTableStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStavke);

        jLabel7.setText("Stavke racuna:");

        jButtonZatvori.setText("Zatvori");
        jButtonZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZatvoriActionPerformed(evt);
            }
        });

        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        jButtonSacuvaj.setText("Sacuvaj izmene");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jButtonObrisiStavku.setText("Obrisi odabranu stavku");
        jButtonObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiStavkuActionPerformed(evt);
            }
        });

        jButtonIzmeniStavku.setText("Izmeni odabranu stavku");
        jButtonIzmeniStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniStavkuActionPerformed(evt);
            }
        });

        jButtonDodajStavku.setText("Dodaj novu stavku");
        jButtonDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxKrojacica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(16, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButtonZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonObrisiStavku)
                        .addGap(43, 43, 43)
                        .addComponent(jButtonIzmeniStavku)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSacuvaj)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonDodajStavku)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButtonIzmeni))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxKrojacica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonObrisiStavku)
                            .addComponent(jButtonIzmeniStavku))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonZatvori)
                            .addComponent(jButtonSacuvaj))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDodajStavku)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZatvoriActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonZatvoriActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        jTextFieldMesto.setEnabled(true);
        jComboBoxKlijent.setEnabled(true);
        jComboBoxKrojacica.setEnabled(true);
        jButtonSacuvaj.setEnabled(true);
        jButtonIzmeni.setEnabled(false);
        jButtonObrisiStavku.setEnabled(true);
        jButtonIzmeniStavku.setEnabled(true);
        jButtonDodajStavku.setEnabled(true);
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        try {
            r.setMestoIzdavanja(jTextFieldMesto.getText());
            r.setKlijent((Klijent) jComboBoxKlijent.getSelectedItem());
            r.setKrojacica((Krojacica) jComboBoxKrojacica.getSelectedItem());

            TableModelStavkeRacuna tm = (TableModelStavkeRacuna) jTableStavke.getModel();
            r.setStavkeRacuna(tm.getLista());
            r.setUkupanIznos(tm.vratiUkupanIznos());

            ClientController.getInstance().promeniRacun(r);

            jTextFieldUkupanIznos.setText(String.valueOf(r.getUkupanIznos()));
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio racun.");
            fpr.refreshTable();
            jTextFieldMesto.setEnabled(false);
            jComboBoxKlijent.setEnabled(false);
            jComboBoxKrojacica.setEnabled(false);
            jButtonSacuvaj.setEnabled(false);
            jButtonIzmeni.setEnabled(true);
            jButtonObrisiStavku.setEnabled(false);
            jButtonIzmeniStavku.setEnabled(false);
            jButtonDodajStavku.setEnabled(false);

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti racun.");
        }
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonIzmeniStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniStavkuActionPerformed
        int row = jTableStavke.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Morate odabrati stavku za izmenu.");
            return;
        }
        TableModelStavkeRacuna tm = (TableModelStavkeRacuna) jTableStavke.getModel();
        StavkaRacuna stavka = tm.getLista().get(row);

        FormIzmenaStavke fis = new FormIzmenaStavke(null, true, stavka);
        fis.setVisible(true);

        // stavka je izmenjena direktno u memoriji kroz referencu
        tm.fireTableDataChanged();
        jTextFieldUkupanIznos.setText(String.valueOf(tm.vratiUkupanIznos()));
    }//GEN-LAST:event_jButtonIzmeniStavkuActionPerformed

    private void jButtonObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiStavkuActionPerformed
        int row = jTableStavke.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Morate odabrati stavku za brisanje.");
            return;
        }
        TableModelStavkeRacuna tm = (TableModelStavkeRacuna) jTableStavke.getModel();
        tm.obrisiStavku(row);
        jTextFieldUkupanIznos.setText(String.valueOf(tm.vratiUkupanIznos()));
    }//GEN-LAST:event_jButtonObrisiStavkuActionPerformed

    private void jButtonDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajStavkuActionPerformed
        FormDodavanjeStavke fds = new FormDodavanjeStavke(null, true);
        fds.setVisible(true);

        StavkaRacuna nova = fds.getNovaStavka();
        if (nova == null) {
            return; // korisnik zatvorio bez dodavanja
        }
        nova.setRacun(r);
        TableModelStavkeRacuna tm = (TableModelStavkeRacuna) jTableStavke.getModel();
        tm.dodajStavku(nova);
        jTextFieldUkupanIznos.setText(String.valueOf(tm.vratiUkupanIznos()));
    }//GEN-LAST:event_jButtonDodajStavkuActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajStavku;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonIzmeniStavku;
    private javax.swing.JButton jButtonObrisiStavku;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JButton jButtonZatvori;
    private javax.swing.JComboBox<Klijent> jComboBoxKlijent;
    private javax.swing.JComboBox<Krojacica> jComboBoxKrojacica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStavke;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldMesto;
    private javax.swing.JTextField jTextFieldUkupanIznos;
    // End of variables declaration//GEN-END:variables

    private void popuniKrojacice() {
        try {
            ArrayList<Krojacica> krojacice = ClientController.getInstance().vratiListuSvihKrojacica();
            jComboBoxKrojacica.removeAllItems();
            for (Krojacica k : krojacice) {
                jComboBoxKrojacica.addItem(k);
            }
        } catch (Exception ex) {
            Logger.getLogger(FormDetaljiRacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private void popuniKlijente() {
        try {
            ArrayList<Klijent> klijenti = ClientController.getInstance().vratiListuSvihKlijenata();
            jComboBoxKlijent.removeAllItems();
            for (Klijent k : klijenti) {
                jComboBoxKlijent.addItem(k);
            }
        } catch (Exception ex) {
            Logger.getLogger(FormDetaljiRacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

}
