/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form_krojacka_usluga;

import domain.KrojackaUsluga;
import forme.MainForm;
import javax.swing.JOptionPane;
import models.TableModelKrojackeUsluge;

/**
 *
 * @author Andjela
 */
public class FormPretragaKrojackeUsluge extends javax.swing.JDialog {

    private MainForm mf;

    /**
     * Creates new form FormPretragaKrojackeUsluge
     */
    public FormPretragaKrojackeUsluge(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.mf = (MainForm) parent;
        setLocationRelativeTo(null);
        setTitle("Pretraga krojacke usluge");
        TableModelKrojackeUsluge model = new TableModelKrojackeUsluge();
        jTableKrojackeUsluge.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldUnos = new javax.swing.JTextField();
        jButtonPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKrojackeUsluge = new javax.swing.JTable();
        jButtonDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Unesite naziv krojacke usluge:");

        jButtonPretrazi.setText("Pretrazi uslugu");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jTableKrojackeUsluge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableKrojackeUsluge);

        jButtonDetalji.setText("Prikazi detalje o odabranoj usluzi");
        jButtonDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldUnos, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPretrazi))
                        .addGap(38, 38, 38))))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jButtonDetalji)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldUnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButtonPretrazi)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonDetalji)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        String unos = jTextFieldUnos.getText();
        TableModelKrojackeUsluge tm = (TableModelKrojackeUsluge) jTableKrojackeUsluge.getModel();
        tm.setParametar(unos);

        if (tm.getRowCount() > 0) {
            JOptionPane.showMessageDialog(this, "Sistem je nasao krojacke usluge po zadatim kriterijumima.");
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje krojacke usluge po zadatim kriterijumima.");
        }
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljiActionPerformed
        int row = jTableKrojackeUsluge.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Morate odabrati krojacku uslugu.");
            return;
        }
        try {
            KrojackaUsluga k = ((TableModelKrojackeUsluge) jTableKrojackeUsluge.getModel()).getSelectedKrojackaUsluga(row);
            JOptionPane.showMessageDialog(this, "Sistem je nasao krojacku uslugu.");
            FormDetaljiKrojackeUsluge fdk = new FormDetaljiKrojackeUsluge(this, true, k);
            fdk.setVisible(true);
            refreshTable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje krojacku uslugu.");
        }
    }//GEN-LAST:event_jButtonDetaljiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetalji;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKrojackeUsluge;
    private javax.swing.JTextField jTextFieldUnos;
    // End of variables declaration//GEN-END:variables

    public void refreshTable() {
        TableModelKrojackeUsluge tm = (TableModelKrojackeUsluge) jTableKrojackeUsluge.getModel();
        tm.refreshTable();
        
        mf.popuniKrojackeUsluge();
    }
}
