/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controller.ClientController;
import domain.Klijent;
import domain.Krojacica;
import domain.KrojackaUsluga;
import domain.Racun;
import domain.StavkaRacuna;
import form_klijent.FormNoviKlijent;
import form_klijent.FormPretragaKlijenta;
import form_krojacka_usluga.FormNovaKrojackaUsluga;
import form_krojacka_usluga.FormPretragaKrojackeUsluge;
import form_racun.FormPretragaRacuna;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.TableModelStavkeRacuna;
import session.Session;

/**
 *
 * @author Andjela
 */
public class MainForm extends javax.swing.JFrame {

    private Krojacica ulogovana;
    private double ukupanIznos;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        jTextFieldUkupanIznos.setEnabled(false);
        setLocationRelativeTo(null);
        setTitle("Glavna forma");
        this.ulogovana = Session.getInstance().getUlogovana();
        Session.getInstance().setMf(this);
        jLabelUlogovana.setText("Ulogovana krojacica: " + ulogovana);

        jTextFieldUkupanIznos.setEditable(false);
        popuniKrojackeUsluge();
        popuniKlijente();
        jTableStavkeRacuna.setModel(new TableModelStavkeRacuna());

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int response = JOptionPane.showConfirmDialog(
                        null,
                        "Da li ste sigurni da zelite da se odjavite?",
                        "Potvrda odjavljivanja",
                        JOptionPane.YES_NO_OPTION
                );

                if (response == JOptionPane.YES_OPTION) {
                    try {
                        ClientController.getInstance().logout(ulogovana);
                        System.exit(0);
                    } catch (Exception ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabelUlogovana = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStavkeRacuna = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonObrisiStavku = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxKrojackaUsluga = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldKolicina = new javax.swing.JTextField();
        jButtonDodajStavku = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxKlijent = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldMesto = new javax.swing.JTextField();
        jButtonSacuvajRacun = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldUkupanIznos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRacun = new javax.swing.JMenu();
        jMenuItemPretraziRacun = new javax.swing.JMenuItem();
        jMenuKrojackaUsluga = new javax.swing.JMenu();
        jMenuItemPretraziUslugu = new javax.swing.JMenuItem();
        jMenuItemDodajNovuUslugu = new javax.swing.JMenuItem();
        jMenuDodajNovogKlijenta = new javax.swing.JMenu();
        jMenuItemPretraziKlijenta = new javax.swing.JMenuItem();
        jMenuItemDodajNovogKlijenta = new javax.swing.JMenuItem();
        jMenuOdjava = new javax.swing.JMenu();
        jMenuItemOdjava = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(591, 657));

        jLabelUlogovana.setText("Ulogovana krojacica");

        jTableStavkeRacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStavkeRacuna);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Kreirajte racun:");

        jButtonObrisiStavku.setText("Obrisi odabranu stavku");
        jButtonObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiStavkuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Dodajte stavku racuna:");

        jLabel3.setText("Odaberite krojacku uslugu:");

        jComboBoxKrojackaUsluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKrojackaUslugaActionPerformed(evt);
            }
        });

        jLabel4.setText("Unesite kolicinu:");

        jButtonDodajStavku.setText("Dodaj stavku");
        jButtonDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxKrojackaUsluga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51)
                        .addComponent(jButtonDodajStavku)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(191, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxKrojackaUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButtonDodajStavku)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 47, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Definisite detalje racuna:");

        jLabel6.setText("Odaberite klijenta:");

        jLabel7.setText("Unesite mesto:");

        jButtonSacuvajRacun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSacuvajRacun.setForeground(new java.awt.Color(102, 102, 255));
        jButtonSacuvajRacun.setText("SACUVAJ RACUN");
        jButtonSacuvajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajRacunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxKlijent, 0, 163, Short.MAX_VALUE)
                    .addComponent(jTextFieldMesto))
                .addGap(72, 72, 72)
                .addComponent(jButtonSacuvajRacun)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBoxKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSacuvajRacun)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel8.setText("Ukupan iznos racuna:");

        jLabel9.setText("din");

        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenuRacun.setText("Racun");

        jMenuItemPretraziRacun.setText("Pretrazite racun");
        jMenuItemPretraziRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretraziRacunActionPerformed(evt);
            }
        });
        jMenuRacun.add(jMenuItemPretraziRacun);

        jMenuBar1.add(jMenuRacun);

        jMenuKrojackaUsluga.setText("Krojacka usluga");

        jMenuItemPretraziUslugu.setText("Pretrazite uslugu");
        jMenuItemPretraziUslugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretraziUsluguActionPerformed(evt);
            }
        });
        jMenuKrojackaUsluga.add(jMenuItemPretraziUslugu);

        jMenuItemDodajNovuUslugu.setText("Dodajte novu uslugu");
        jMenuItemDodajNovuUslugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajNovuUsluguActionPerformed(evt);
            }
        });
        jMenuKrojackaUsluga.add(jMenuItemDodajNovuUslugu);

        jMenuBar1.add(jMenuKrojackaUsluga);

        jMenuDodajNovogKlijenta.setText("Klijent");

        jMenuItemPretraziKlijenta.setText("Pretrazite klijenta");
        jMenuItemPretraziKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretraziKlijentaActionPerformed(evt);
            }
        });
        jMenuDodajNovogKlijenta.add(jMenuItemPretraziKlijenta);

        jMenuItemDodajNovogKlijenta.setText("Dodajte novog klijenta");
        jMenuItemDodajNovogKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajNovogKlijentaActionPerformed(evt);
            }
        });
        jMenuDodajNovogKlijenta.add(jMenuItemDodajNovogKlijenta);

        jMenuBar1.add(jMenuDodajNovogKlijenta);

        jMenuOdjava.setText("Odjavite se");

        jMenuItemOdjava.setText("Odjava");
        jMenuItemOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOdjavaActionPerformed(evt);
            }
        });
        jMenuOdjava.add(jMenuItemOdjava);

        jMenuBar1.add(jMenuOdjava);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUlogovana)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jButtonObrisiStavku)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelUlogovana)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonObrisiStavku)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPretraziRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretraziRacunActionPerformed
        FormPretragaRacuna fpr = new FormPretragaRacuna(this, true);
        fpr.setVisible(true);
    }//GEN-LAST:event_jMenuItemPretraziRacunActionPerformed

    private void jButtonObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiStavkuActionPerformed

        int row = jTableStavkeRacuna.getSelectedRow();

        if (row >= 0) {
            TableModelStavkeRacuna tm = (TableModelStavkeRacuna) jTableStavkeRacuna.getModel();
            tm.obrisiStavku(row);

            ukupanIznos = tm.vratiUkupanIznos();
            jTextFieldUkupanIznos.setText(String.valueOf(ukupanIznos) + "din");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Morate odabrati stavku racuna za brisanje.");
        }
    }//GEN-LAST:event_jButtonObrisiStavkuActionPerformed

    private void jMenuItemOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOdjavaActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "se odjavite?", "Potvrda odjavljivanja", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            try {
                ClientController.getInstance().logout(ulogovana);
                new LoginForm().setVisible(true);
                Session.getInstance().setUlogovana(null);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItemOdjavaActionPerformed

    private void jMenuItemDodajNovogKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajNovogKlijentaActionPerformed
        FormNoviKlijent fnk = new FormNoviKlijent(this, true);
        fnk.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajNovogKlijentaActionPerformed

    private void jMenuItemPretraziKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretraziKlijentaActionPerformed
        FormPretragaKlijenta fpk = new FormPretragaKlijenta(this, true);
        fpk.setVisible(true);
    }//GEN-LAST:event_jMenuItemPretraziKlijentaActionPerformed

    private void jMenuItemDodajNovuUsluguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajNovuUsluguActionPerformed
        FormNovaKrojackaUsluga fnku = new FormNovaKrojackaUsluga(this, true);
        fnku.setVisible(true);
    }//GEN-LAST:event_jMenuItemDodajNovuUsluguActionPerformed

    private void jMenuItemPretraziUsluguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretraziUsluguActionPerformed
        FormPretragaKrojackeUsluge fpku = new FormPretragaKrojackeUsluge(this, true);
        fpku.setVisible(true);
    }//GEN-LAST:event_jMenuItemPretraziUsluguActionPerformed

    private void jButtonDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajStavkuActionPerformed
        if (jTextFieldKolicina.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti kolicinu.");
            return;
        }

        KrojackaUsluga krojackaUsluga = (KrojackaUsluga) jComboBoxKrojackaUsluga.getSelectedItem();
        int kolicina = Integer.parseInt(jTextFieldKolicina.getText());

        if (kolicina <= 0) {
            JOptionPane.showMessageDialog(this, "Kolicina mora biti veca od 0.");
            return;
        }

        StavkaRacuna sr = new StavkaRacuna(null, -1, kolicina, krojackaUsluga.getCena(),
                (kolicina * krojackaUsluga.getCena()), krojackaUsluga);

        TableModelStavkeRacuna tm = (TableModelStavkeRacuna) jTableStavkeRacuna.getModel();

//        if (tm.postojiKrojackaUsluga(krojackaUsluga)) {
//            JOptionPane.showMessageDialog(this, "Odabrana usluga je vec dodata na racun");
//            return;
//        }
        tm.dodajStavku(sr);

        ukupanIznos = tm.vratiUkupanIznos();
        jTextFieldUkupanIznos.setText(String.valueOf(ukupanIznos));
        jTextFieldKolicina.setText("");
    }//GEN-LAST:event_jButtonDodajStavkuActionPerformed

    private void jComboBoxKrojackaUslugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKrojackaUslugaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxKrojackaUslugaActionPerformed

    private void jButtonSacuvajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajRacunActionPerformed
        try {
            TableModelStavkeRacuna tm = (TableModelStavkeRacuna) jTableStavkeRacuna.getModel();
            String mestoIzdavanja = jTextFieldMesto.getText();
            Klijent klijent = (Klijent) jComboBoxKlijent.getSelectedItem();
            Racun racun = new Racun(-1, new Date(), mestoIzdavanja, ukupanIznos,
                    ulogovana, klijent, tm.getLista());

            ClientController.getInstance().ubaciRacun(racun);
            jTextFieldUkupanIznos.setText("");
            ukupanIznos = 0;
            tm.getLista().clear();
            tm.fireTableDataChanged();
            JOptionPane.showMessageDialog(this, "Sistem je ubacio racun.");
            jTextFieldMesto.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ubaci racun.");
            //            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSacuvajRacunActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajStavku;
    private javax.swing.JButton jButtonObrisiStavku;
    private javax.swing.JButton jButtonSacuvajRacun;
    private javax.swing.JComboBox<Klijent> jComboBoxKlijent;
    private javax.swing.JComboBox<KrojackaUsluga> jComboBoxKrojackaUsluga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelUlogovana;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDodajNovogKlijenta;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemDodajNovogKlijenta;
    private javax.swing.JMenuItem jMenuItemDodajNovuUslugu;
    private javax.swing.JMenuItem jMenuItemOdjava;
    private javax.swing.JMenuItem jMenuItemPretraziKlijenta;
    private javax.swing.JMenuItem jMenuItemPretraziRacun;
    private javax.swing.JMenuItem jMenuItemPretraziUslugu;
    private javax.swing.JMenu jMenuKrojackaUsluga;
    private javax.swing.JMenu jMenuOdjava;
    private javax.swing.JMenu jMenuRacun;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStavkeRacuna;
    private javax.swing.JTextField jTextFieldKolicina;
    private javax.swing.JTextField jTextFieldMesto;
    private javax.swing.JTextField jTextFieldUkupanIznos;
    // End of variables declaration//GEN-END:variables

    public void popuniKrojackeUsluge() {
        try {
            ArrayList<KrojackaUsluga> usluge = ClientController.getInstance().vratiListuSvihKrojackihUsluga();

            jComboBoxKrojackaUsluga.removeAllItems();

            for (KrojackaUsluga usluga : usluge) {
                jComboBoxKrojackaUsluga.addItem(usluga);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void popuniKlijente() {
        try {
            ArrayList<Klijent> klijenti = ClientController.getInstance().vratiListuSvihKlijenata();

            jComboBoxKlijent.removeAllItems();

            for (Klijent klijent : klijenti) {
                jComboBoxKlijent.addItem(klijent);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
